---
- name: Parcheo de servidores Windows
  hosts: windows_servers
  become: false
  gather_facts: true

  tasks:
    - name: Rol Parcheo WINDOWS
      ansible.builtin.include_role:
        name: patch_windows
      when: ansible_facts['os_family'] == 'Windows'
